### ISSUE TITLE
Admin Interface

### ISSUE THREAD

**Issue by tehfink** [coleifer/django-generic-m2m#2]
What do you think of a RelatedObjectsDescriptor widget for the admin, such as SelectMultiple?

**Comment by shaunagm** [comment]
Both of the links @jpic provided no longer work.  Are there any other example widgets for viewing generic m2m in the admin?

**Comment by jpic** [comment]
This is because django-generic-m2m is natively supported by
django-autocomplete-light 2.x as an optionnal dependency.

Read the tutorial and docs about generic m2m if needed:
http://django-autocomplete-light.readthedocs.org/en/stable-2.x.x/generic.html
